---
version: '2'
services:
  login_api:
    build:
      context: ./api/login_api
      dockerfile: Dockerfile
    volumes:
      - ./api/login_api:/opt/login_api
    links:
      - db
    ports:
      - "4001:4001"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
